# Copyright 2023 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Cert Manager config
apiVersion: skaffold/v3
kind: Config
metadata:
  name: cert-manager-cfg
manifests:
  rawYaml:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
deploy:
  kubectl: {}
---
#OpenTelemetry Installation
apiVersion: skaffold/v3
kind: Config
metadata:
  name: open-telemetry-cfg
manifests:
  rawYaml:
  - https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command: ["sh", "-c", "echo Waiting for cert-manager stabilization; sleep 90"]
      after:
        - host:
            command: ["sh", "-c", "sleep 10"]
---
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: genai-quickstart-cfg
requires:
- configs: ["genai-api-cfg"]
  path: ./api/genai_api/skaffold.yaml

- configs: ["stable-diffusion-api-cfg"]
  path: ./api/stable_diffusion_api/skaffold.yaml

- configs: ["vertex-gemini-api-cfg"]
  path: ./api/vertex_gemini_api/skaffold.yaml

- configs: ["vertex-chat-api-cfg"]
  path: ./api/vertex_chat_api/skaffold.yaml

- configs: ["vertex-code-api-cfg"]
  path: ./api/vertex_code_api/skaffold.yaml

- configs: ["vertex-image-api-cfg"]
  path: ./api/vertex_image_api/skaffold.yaml

- configs: ["vertex-text-api-cfg"]
  path: ./api/vertex_text_api/skaffold.yaml

- configs: ["stable-diffusion-endpt-cfg"]
  path: ./image/stable_diffusion/skaffold.yaml
